# Generated by Django 5.0.4 on 2024-05-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_postreactions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostReactions",
        ),
    ]
