# Generated by Django 5.0.4 on 2024-05-03 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_delete_postreactions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostReactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coffee", models.PositiveBigIntegerField(default=0)),
                ("rocket", models.PositiveBigIntegerField(default=0)),
                ("thumbsUp", models.PositiveBigIntegerField(default=0)),
                ("heart", models.PositiveBigIntegerField(default=0)),
                ("wow", models.PositiveBigIntegerField(default=0)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="core.blogpost",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Postreactions",
            },
        ),
    ]
