# Generated by Django 5.0.4 on 2024-05-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_blogpost_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(default=None, upload_to="uploads/posts/"),
        ),
    ]
