# Generated by Django 5.0.4 on 2024-05-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_blogpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                default="media/uploads/posts/4.png", upload_to="uploads/posts/"
            ),
        ),
    ]
