# Generated by Django 5.0.4 on 2024-05-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_postreactions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostReactions",
        ),
    ]
