# Generated by Django 5.0.4 on 2024-05-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_reply"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
